### PR TITLE
Make initial page look like other example and remove storyboard.

### PR DESCRIPTION
**Pull request by MacMeDan**
## Pull request checklist

- [X] All tests pass. Demo project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊

## What's in this pull request?

> Removed the Storyboard all together. Made the Initial view look more like the current example project. Fixed some issues we were having with settings.

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @MacMeDan ! 😄 

I'd rather keep `Main.storyboard` for now, sticking with the default Xcode setup

**Comment by jessesquires** [comment]
@MacMeDan -- also, there's a ton of unrelated merge commits:
https://github.com/jessesquires/JSQMessagesViewController/pull/1734/commits

we really need to try to avoid this. it makes it incredibly hard to review, and makes commit history really unclean. 

I suggest the following workflow:

1. Fresh fork of the project
2. Specify `upstream` to point to the main repo: https://help.github.com/articles/configuring-a-remote-for-a-fork/
3. `git checkout develop` Checkout develop branch 
4. `git pull upstream develop` Pull main repo develop
5. `git branch my-branch` Branch from latest develop
6. Do work
7. `git commit -am "commit msg"` Make 1 single commit and push
8. Use github to submit PR from `my-branch` into `jessesquires/develop`

(this might not be *exact*, but that's the gist)

You should never have to `git merge develop` with this flow.

@Lucashuang0802 - Your PRs have been really clean, maybe you can share how you do this if it's any different than what I've described?

**Comment by MacMeDan** [comment]
@jessesquires Sorry about that it seems that the Settings view has a broken outlet which led me to swapping out that view making the pull request much larger then it should have been. Sorry about that.

**Comment by MacMeDan** [comment]
And of coarse I separated the code out and made a new pull request and then saw that you want to keep the `MainStoryBoard` I just thought it would be nicer to have it all programmatically for testing purposes.

**Comment by Lucashuang0802** [comment]
I love using `git rebase` interactive mode to squash commits into one. And `git push --force` is my friend as well. But, you have to be very clear about where each branch starts and ends. I normally use *SourceTree* to help me understand how branches and commits look in the repo. So, my normal step will be:

1. pull origin and fetch upstream (update your fork and remote)
2. pick your desired working branch, rebase to upstream and solve conflicts if necessary
3. `git push --force`, I don't suggest this normally because it will update whatever you have from your local
4. Do your work, commit and push
5. submit PRs
6. modify and squash using `git rebase -i HEAD~<# number of commits #>` if necessary.

Let me know if that's a better approach. I am not a fan of using merge feature because it will create a lot of merging commits that can be squashed.

**Comment by MacMeDan** [comment]
so @Lucashuang0802 I also use source tree. From my understanding you are using source tree to see the grand picture but then use the command line to preform these other steps.

**Comment by Lucashuang0802** [comment]
@MacMeDan. Yes, I use it for the grand picture. And do all my git operations in CLI. 😃

**Pull request closed without merging**
