### PR TITLE
Dynamic type support

### PR DESCRIPTION
**Pull request by MacMeDan**
## Pull request checklist

- [✅] This fixes issue #497
- [✅] All tests pass. Demo project builds and runs.
- [✅] I have resolved any merge conflicts.
- [✅] I have squashed my commits into 1 commit.
- [✅] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: :muscle::sunglasses::facepunch:

## What's in this pull request?
This pull request adds support for dynamic type in both the incoming and outgoing bubbles, the Top label and top and bottom message labels. 
>...

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @MacMeDan !

Looks like there are some unrelated commits in here? (The pod changes, etc.)

**Comment by MacMeDan** [comment]
ya Ill look into it.

**Comment by MacMeDan** [comment]
My bad on that one @jessesquires I didn't realize I did that on my forked/develop branch :)

**Comment by MacMeDan** [comment]
This is fixed.

**Comment by jessesquires** [comment]
Thanks @MacMeDan !

If you go to the commits tab, it looks like there are still some issues. Some unrelated commits, and not squashed. https://github.com/jessesquires/JSQMessagesViewController/pull/1467/commits

Also looks like some merge conflicts :grin:

**Comment by jessesquires** [comment]
hey @MacMeDan -- want to submit a fresh PR for this and sync up with the changes in #1169?

**Comment by MacMeDan** [comment]
ya I'll take a look through this.

**Comment by jessesquires** [comment]
replaced by #1607

**Pull request closed without merging**
