### PR TITLE
 fixes issue #1218

### PR DESCRIPTION
**Pull request by prashantcraju**
## Pull request checklist
- [X] All tests pass. Demo project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
## What's in this pull request?

A very minor change that prevents the app from crashing

### CODE REVIEW

**Comment by prashantcraju** [comment]
Merging with the latest develop branch

**Comment by jessesquires** [comment]
Thanks @prashantcraju !

Can you explain how this fixes the issue?

**Comment by Lucashuang0802** [comment]
Hey @prashantcraju, I am also curious the reason. OP from #1218 said it only had a warning. I'm just wondering it crashes or?

**Comment by prashantcraju** [comment]
@jessesquires The issue didn't mention it, but when I tested it, it repeated crashed. Making the change that I did stopped the app from crashing.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Pull request closed without merging**
