### PR TITLE
Fix for #1268, bottom content insets

### PR DESCRIPTION
**Pull request by mbalex99**
## Pull request checklist

- [ x ] All tests pass. Demo project builds and runs.
- [ x ] I have resolved any merge conflicts.
- [ x ] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: x

## What's in this pull request?

This adds an additional property similar to `topContentAdditionalInset` called `bottomContentAdditionalInset` which adds extra room to the bottom of the collection view.

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks for working on this @mbalex99 ! 👍

**Comment by mbalex99** [comment]
np @jessesquires it was tiny but I need some additional buttons above the toolbar

**Comment by jessesquires** [comment]
⚠️ **To be merged for 8.0. Do not yet merge.** ⚠️

**Comment by jessesquires** [comment]
Hey @mbalex99 ! 😄 

Sorry this fell through the cracks. Do you mind rebasing and resolving conflicts?

**Comment by Lucashuang0802** [comment]
@mbalex99 I'm so sorry I submitted a duplicate PR #1737. Can you change to use one property like #1737 did? But don't follow the way I did, @jessesquires did not really review it. Mine will be closed when you are ready. Thx.

**Comment by jessesquires** [comment]
Thanks again @mbalex99 ! 😄 

We've decided to go with a slightly different solution here.  50ce785

**Pull request closed without merging**
