### PR TITLE
Implemented #810: An easier way to handle custom menu actions.

### PR DESCRIPTION
**Pull request by sebastianludwig**
Any feedback appreciated.

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @sebastianludwig ! :+1: Very nice, very clean.

Can you explain the 3 new cells methods under `#pragma mark - Menu actions` ?

**Comment by sebastianludwig** [comment]
They play together with `+registerAction:`. After registering an action a cell behaves like it would have implemented that method. It's a generic way of handling custom methods with as little code as possible.

Say you register the action `[JSQMessagesCollectionViewCell registerAction:@selector(myCustomAwesomeness:)]` the cell will respond with `YES` if asked `respondsToSelector:@selector(myCustomAwesomeness:)`. And you can even send the cell the `myCustomAwesomeness:` message: `[cell myCustomAwesomeness:sender]`. The runtime sees that the cell does not really implement that method but instead of raising an error immediately the cell gets the chance to forward the message. That's what the bottom two methods are for.

The `methodSignatureForSelector:` is used to create the `NSInvocation` object passed to `forwardInvocation:`. `forwardInvocation:` does the actual magic by calling out to the delegate which in turn propagates to the `UICollectionViewDelegate`.

The drawback of the static property is that all message cells share the same actions, even across multiple `JSQMessageViewControllers`. In my opinion that's not too much of drawback, because

1. It's probably rare to have multiple `JSQMessageViewControllers` (where you want different actions)
1. It's should be still possible to control which actions are shown, my modifying `[[UIMenuController sharedMenuController] setMenuItems:@[]]`
1. The general situation is much better than before and whoever is in need can further improve it.

**Comment by jessesquires** [comment]
@sebastianludwig - Thanks!

I hate digging around in the runtime like this, but for *this* situation... `¯\_(ツ)_/¯` it doesn't look like there's a better way. Man, I really hate how this API works — it breaks all kinds of software patterns and principles.

I do want to merge this, but I'm not sure about the right time/place yet.

**Comment by sebastianludwig** [comment]
A pleasure, @jessesquires 

Well, with this I can't help you - except maybe that I'd love to use it and at best from the official repository ;-)

**Comment by sebastianludwig** [comment]
@jessesquires, any further thoughts on this?

**Comment by jessesquires** [comment]
Here's my current plan:

1. Push out [6.1.4](https://github.com/jessesquires/JSQMessagesViewController/milestones) as soon as I can
2. Merge this, and fix #684 
3. Release 7.0

(other existing milestones will need to be moved around)

**Comment by sebastianludwig** [comment]
:+1:

**Comment by jessesquires** [comment]
Hey @sebastianludwig - pushing out 7.0 today. This won't make it in for this release (mostly bug fixes, and minor API changes for swift compatibility).

However, this will be in the next!

**Comment by jessesquires** [comment]
Thanks @sebastianludwig ! Merging now.

I'm going to change `static NSMutableArray *jsqMessagesCollectionViewCellActions` to a mutable set instead -- we don't want duplicates. Let me know if you think this will cause any issues.

**Comment by sebastianludwig** [comment]
Oh no, you're totally right. Thanks for merging!

**Comment by nikkoss** [comment]
I checked out the demo app and found that "Custom action" is also added to the new message text field. Is there any way to add "Custom action" only to cells but not the input text field?

I tried to add to JSQMessagesComposerTextView

```
- (BOOL)canPerformAction:(SEL)action withSender:(id)sender {
    if (action == @selector(customAction:)) {
        // Return YES only if it's possible to perform the action at this time
        return NO;
    }

    return [super canPerformAction:action withSender:sender];
}
```
but "Custom action" is still there.

**Comment by jessesquires** [comment]
@nikkoss - i think you'll want to modify the `UIMenuController` items instead

**Comment by relatedcode** [comment]
@jessesquires @nikkoss @sebastianludwig Sorry for asking, but is this "long press custom menu" working properly or it's still in progress? Thanks!

**Comment by sebastianludwig** [comment]
I will try to look into issue reported by @nikkoss later - otherwise it's working fine.

**Comment by relatedcode** [comment]
@sebastianludwig Ok, thanks! Do you have any available sample implementation? :)

**Comment by sebastianludwig** [comment]
@relatedcode There is a working example in the demo project (slightly modified by the PR above).

**Comment by relatedcode** [comment]
@sebastianludwig I see. Thanks! :)

**Comment by relatedcode** [comment]
@sebastianludwig Do you have any idea how to solve this situation?

http://relatedcode.com/JSQMessagesViewController.mp4

Latest, unchanged version. I experience the same all the time.

**Comment by sebastianludwig** [comment]
@relatedcode see #1026 and #1027

**Comment by relatedcode** [comment]
@sebastianludwig You are AWESOME! :) Thanks man!

**Pull request merged**
