### PR TITLE
Conversations list in Swift Example.

### PR DESCRIPTION
**Pull request by MacMeDan**
## Pull request checklist

- [X] All tests pass. Demo project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊

## What's in this pull request?

> Added Conversations list with example group Conversation and Regular conversation.

### CODE REVIEW

**Comment by MacMeDan** [comment]
@GianniCarlo Here is the conversations list back.

**Comment by GianniCarlo** [comment]
Nice!, @MacMeDan did you get a chance to check out my [pull request] (https://github.com/jessesquires/JSQMessagesViewController/pull/1639) about locations?

**Comment by MacMeDan** [comment]
@GianniCarlo I have not yet I am waiting for a few pull requests to get merged and then I will take a look.

**Comment by GianniCarlo** [comment]
No worries 👍

On Wednesday, 8 June 2016, Dan Leonard <notifications@github.com> wrote:

> @GianniCarlo <https://github.com/GianniCarlo> I have not yet I am waiting
> for a few pull requests to get merged and then I will take a look.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jessesquires/JSQMessagesViewController/pull/1655#issuecomment-224693559>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANdYM9IbdAvIHKlwvkA0eAyUKIKA1Z2wks5qJxE_gaJpZM4IwSVM>
> .
>


-- 

You can contact me privately!
Message me now
<https://messenger.criptext.com/private/imrur3bn9h4yw7aegrd7k3xr>
Gianni Carlo

**Comment by MacMeDan** [comment]
Hey @jessesquires I updated this guy with all the changes from develop. Is there anything else that we need for this guy.

**Comment by MacMeDan** [comment]
Yae and all the checks passed.

**Comment by jessesquires** [comment]
👍

**Pull request merged**
