### PR TITLE
Added sendButton and sendButtonEnabled properties to JSQMessagesInputToo...

### PR DESCRIPTION
**Pull request by Stunner**
...lbar, which allows for easier access, and to specify whether to keep the button (dis)enabled for the user’s purposes.

### CODE REVIEW

**Comment by Stunner** [comment]
@jessesquires this is required by my organization's app as it allows the app the ability to disable/enable the send button according to other factors other than having text in the text field. For example, my app only allows the send button to be enabled when a valid recipient has been selected. Please let me know what else (if any) is required to get this merged back in.

**Comment by wdcurry** [comment]
I still consider myself a noob here on github, so i must ask: how do i can access to this update? This is critical for proper management of external factors, reachability being one of them.

**Comment by Stunner** [comment]
It is a solid question. What you want to do is to merge an upstream repository into your fork: https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/ So in this case your command would be (after switching to the branch that you want these changes to go into): `git pull https://github.com/Stunner/JSQMessagesViewController.git develop`.

**Comment by wdcurry** [comment]
Thank you Stunner.. I will look into that. Although, for my purpose, it might be just as easier to code my requirements into my local version. It simply requires an extraneous bool that tracks whether we have net access, and if not, to not reset the enabled property.

**Comment by Stunner** [comment]
Design wise it is better to modularize your code with encapsulation and all that good stuff. Good architecture dictates that no class in JSQMessagesViewController should be concerned with checking reachability -- that should be done external to the library, but the library needs to expose a method that allows for toggling of the send button. Additionally, this change has been tested and deployed to production within our app so you can be assured it is robust and works.

**Comment by Lucashuang0802** [comment]
Hmm, this is interested. Jus want to understand better by asking the following questions:smiley:\:
- Why did we have `toggleSendButtonEnabled` method? Can't we enable/disable the send button automatically based on the text?
- What's the purpose to disable the send button when there is not text?

**Comment by Stunner** [comment]
Please read the conversation above. I think it would answer your questions.

**Comment by Lucashuang0802** [comment]
@Stunner ah, my bad. 👍 . One comment is, I don't think exposing `sendButton` is useful. @jessesquires wdyt?

**Comment by Lucashuang0802** [comment]
I think it's duplicate with #1609. 😄

**Comment by jessesquires** [comment]
Thanks @Stunner ! 😄 

We've solved this in a slightly different way in #1609

**Pull request closed without merging**
