### PR TITLE
Add initalTableViewController programatically. Remove its storyboard and add navigation to get back.

### PR DESCRIPTION
**Pull request by MacMeDan**
## Pull request checklist

- [X] All tests pass. Demo project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation:  💪😎👊

## What's in this pull request?

> Remove the storyboard for the initalTabelView and add it programatically.  Add navigation to the chatView and Settings view to get back here.

### CODE REVIEW

**Comment by MacMeDan** [comment]
So @jessesquires do we not want to do this because it removes the need for the storyboard. I still think this is the direction we should head.

**Comment by jessesquires** [comment]
do we need to close #1734 ?

**Comment by jessesquires** [comment]
@MacMeDan do we still need this after merging #1750 ?

**Comment by MacMeDan** [comment]
nope sorry I forgot this was still here.

**Pull request closed without merging**
