### PR TITLE
Swift example added with heavy comments. 

### PR DESCRIPTION
**Pull request by MHaroonBaig**
I haven't tinkered the original branch, just added a separate sandboxed folder featuring a whole example on how to use JSQMessagesViewController in Swift. I've gone through the Firebase' implementation, but they were using an old release, and the use-case of JSQMessagesViewController wasn't very much clear because it was too much congested with the Firebase code base. I cleaned out the unnecessary things and the Firebase code base, added some bits and now we're here. A pure swift example.

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @MHaroonBaig !

Looks like the entire library has been duplicated — we don't want that.

In a new root-level directory, `Swift-Example/`, we'll want to create a new project that references the original source in `JSQMessagesViewController/` but doesn't duplicate it.

**Comment by MHaroonBaig** [comment]
Oh Ok ! Got it. 
Will do it in that way, Gonna commit it soon.

**Comment by MHaroonBaig** [comment]
@jessesquires I've made some changes. The example project is now directly referring to the original source. 
As ```JSQSystemSoundPlayer``` isn't there, so I've added the original source directly. I think in that way, a user can test out the JSQMessagesView right away, without installing any additional things.

**Comment by jawwad** [comment]
The Swift code here helped me out a lot. The Firebase implementation uses a much older version of the library. Thanks @MHaroonBaig.

**Comment by jessesquires** [comment]
Thanks @MHaroonBaig ! :smile: 

We've got some big changes coming up, so I'm going to hold off on this for now.

For the 8.0 release, we'll have better support for swift and that will be a better time to include an even better swift demo project

**Pull request closed without merging**
