### PR TITLE
Fix the non modular error within Xcode7.1

### PR DESCRIPTION
**Pull request by baoluo**

### CODE REVIEW

**Comment by baoluo** [comment]
I don't know why Travis doesn't find the file, maybe because it's not linked with JSQSystemSound, but it works

**Comment by jessesquires** [comment]
hey @baoluo - sounds like you have something wrong with your xcode project setup. this change shouldn't make a difference.

**Comment by baoluo** [comment]
Hello @jessesquires,

Thank you for your response, it does't change anything for you, but for those who use Xcode7.1 and Swift it will. 

I made this project https://github.com/processone/xmpp-messenger-ios, and some user reported the issue when they upgraded to Xcode 7.1

**Comment by svtechnology** [comment]
I am using Xcode 7.1 with Swift and we into heavy internal testing but no one has yet reported any issue on these lines... (yet)

**Comment by baoluo** [comment]
I can assure you that there is people out there including me who have this problem. 

As I said, it doesn't change anything for the rest of you, it just solve the issue for us.

**Comment by jessesquires** [comment]
I'm using Xcode 7.1. Built and ran the demo project without any issues.

**Comment by baoluo** [comment]
This is the opened issue, it will only show the error from the xmppFramework, but when I fixed these errors, one in JSQMessageViewController popped up. https://github.com/processone/xmpp-messenger-ios/issues/15

**Comment by abbasmousavi** [comment]
@jessesquires, @svtechnology  Many other projects have the same issue, just for an example, please check these issues in Mantle and ParsePlatform projects:

https://github.com/Mantle/Mantle/issues/626
https://github.com/ParsePlatform/ParseFacebookUtils-iOS/issues/2

Non-modular import statements in Objective-C pods in some cases can cause problems for dependent Swift pods.

**Comment by jessesquires** [comment]
@abbasmousavi - interesting. I'll look into this more.

**Comment by nathanielescribano** [comment]
i had to do this as well to get my app to build

**Comment by marco1981** [comment]
This PR doesn't compile since you need also add ```use_frameworks!``` into Podfile and run ```pod install``` using cocoapods 0.39.0. I've created a similar pull request https://github.com/jessesquires/JSQMessagesViewController/pull/1325 
See also issue: https://github.com/jessesquires/JSQMessagesViewController/issues/1322

**Comment by baoluo** [comment]
@marco1981 Of course you have to put the use_frameworks! into the Podfile, it's mandatory if you use Pod with Swift files.

**Comment by jessesquires** [comment]
More info:

https://github.com/CocoaPods/CocoaPods/issues/4420

https://github.com/CocoaPods/CocoaPods/issues/4056#issuecomment-143187681

>• If you get an error stating "Include of non-modular header inside framework module" for a 
framework that previously compiled, make sure the "Always Search User Paths" 
build setting is set to "No". The default is "Yes" only for legacy reasons. (22784786)

**Comment by jessesquires** [comment]
This will have to wait until after the `7.2.1` release.

I've marked it for the `8.0.0` milestone, which is when iOS 7 will be dropped.

iOS 7 does not support frameworks, which is why we can't make this change right now.

**Comment by jessesquires** [comment]
fixed by #1649

**Pull request closed without merging**
