### PR TITLE
Fix incorrect toolbar position when keyboard changes its position

### PR DESCRIPTION
**Pull request by erysaj**
This is a fix for issue #906 

I expect this to be merged after other my toolbar position related PRs (did not test without them)

### CODE REVIEW

**Comment by erysaj** [comment]
The goal is to not miss any `keyboardView.frame` changes

Currently there is a few sources about keyboard's frame changes: keyboard notifications and
KVO on keyboard's view.
However that does not work well:
* `UIKeyboardDidChangeFrameNotification` seems to be posted only if user interacts with keyboard "directly" --- open / dismiss / undock / drag, but more subtle changes (see issue description) are not reported
* Lifespan of KVO is not correct. When keyboard is undocked `UIKeyboardDidHideNotification` is posted and `JSQMessagesKeyboardController` decides that keyboard is really going to hide and stops observing.
* `UIView` is not KVO-compliant ([generally Apple-supplied classes aren't unless documented](https://developer.apple.com/library/ios/documentation/General/Conceptual/DevPedia-CocoaCore/KVO.html#//apple_ref/doc/uid/TP40008195-CH16-SW1))

The solution has a few ingredients:
* Detect properly keyboard state. All changes are always accompanied by `UIKeyboardDidChangeFrameNotification` notification, so that's where I check for changes.
Keyboard's visibility is determined by examining input accessory view and "dockedness" by inspecting
keyboard's frame
* to overcome KVO-compliance issue observe keyboard view's layer for properties that affect the resulting frame (see [this SO answer](http://stackoverflow.com/a/19687115))

**Comment by chrisballinger** [comment]
@erysaj Awesome! From my testing this seems to fix the issue we were having where the keyboard was obscuring the toolbar.

**Comment by chrisballinger** [comment]
Spoke too soon. Looks like after showing and hiding the view enough times the keyboard listener still becomes de-synced with the actual state of the keyboard and ends up covering the inputToolbar.

**Comment by erysaj** [comment]
@chrisballinger Thanks for feedback
Could you provide more details:
* device / OS
* did you get this behavior in demo project or in your own setup?
* as I noted in the first comment I developed this patch on top of other toolbar fixes (#897 and #880). Hope you had those applied too
* precise steps to reproduce would also be great

**Comment by chrisballinger** [comment]
@erysaj Here's an issue describing my problem more in detail with a reproducible test case: https://github.com/jessesquires/JSQMessagesViewController/issues/941

When I tested before I merged all of your pull requests together, and the problem is definitely worse after merging them.

**Comment by aviz** [comment]
This fixes my problem with input toolbar... why it's not merged ?

**Comment by jessesquires** [comment]
Thanks @erysaj! 😄 

This hould be fixed by 752fd38aa8b899cbe2e21b6595de58920977bfc2

**Pull request closed without merging**
