### PR TITLE
Added 'bulk delete/edit' mode.

### PR DESCRIPTION
**Pull request by skeeet**
See https://github.com/jessesquires/JSQMessagesViewController/issues/235.
Pretty simple implementation (overlay supplementary views on top of cells + offset cell).
Not breaking existing API.

### CODE REVIEW

**Comment by jessesquires** [comment]
thanks for working on this @skeeet ! 

can you post a screenshot/GIF/video?

**Comment by skeeet** [comment]
Sure. 
Will post after some face-lifting and fixing couple of bugs.

**Comment by skeeet** [comment]
@jessesquires 
Here is how it looks like.
animation

**Comment by gmansata6290** [comment]
how to implement this feature in my application? Can you help me out? @skeeet

**Comment by skeeet** [comment]
@gmansata6290
Check demo app in 'feature/mass_delete' branch of my fork. It is pretty much narrows down to using "isEditing" flag and couple of delegate callbacks.

**Comment by gmansata6290** [comment]
I have integrated JSQ library using Cocoa Pods, But for delete bulk message function I'm unable to add header files to new class JSQMessagesEditCollectionOverlayView . 
It shows error header file not found.
Can you please suggest the right approach.

**Comment by Slessi** [comment]
I would also like this feature !

**Comment by Slessi** [comment]
Note: Have a bug when using inside my app, tapping "Load earlier messages" causes the selected messages to incorrectly become deselected and instead have the new messages (which have now modified the indexes) to be selected instead

i.e. If a page is 10 messages and I select index 7 for editing, upon pressing load earlier messages I would expect index 17 to now be selected but instead the "new" index 7 is selected

**Comment by gmansata6290** [comment]
@Slessi can you give me the sample code or guide me the right approach for deleting individual chat message?

**Comment by Slessi** [comment]
@gmansata6290 I wasn't deleting any messages here, just used the "Load earlier messages" functionality of JSQ.

I fixed this on a fork I made, by switching out:
```objective-c
[self.selectedEditingIndexPaths containsObject:indexPath]
```

With a new delegate function
```objective-c
[self isEditableItemSelectedAtIndexPath:indexPath]
```

Since index paths change if you load earlier messages, you won't be pointing to the right ones anymore

**Comment by ignacio-chiazzo** [comment]
@skeeet @jessesquires @gmansata6290 @Slessi Is there an update of this feature? I need to implement this feature ASAP.

**Comment by alexanderlipsett** [comment]
@skeeet @jessesquires any movement on this feature? I could definitely use this as well.

**Comment by skeeet** [comment]
@ignacio-chiazzo @alexanderlipsett sorry guys, no plans to work on this on near future. Feel free to fork and do any changes.

**Comment by Slessi** [comment]
@ignacio-chiazzo 

I had fixed some of the issues that (I personally) ran into with this feature, and since implementing it my app hasn't had run into problems. Shall I create a new PR from my fork?

**Comment by ignacio-chiazzo** [comment]
@Slessi Good, Could you please create a fork, add your change and rebase over develop? Would be better! If there are a lot of conflict with _development_ don't worry do it over 7.3.4 (I only need any version after 7.0.0) Thank u!

**Comment by TheEngineerz** [comment]
How I can integrate this feature into my app. Where I have installed this library using Pods

**Comment by TheEngineerz** [comment]
@Lucashuang0802  I am totally unable to understand how I can add Multiple selection features in my app. Kindly help me if you can. Or give me any good direction where to go

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Pull request closed without merging**
