### PR TITLE
Extend delegate methods for JSQMediaItem

### PR DESCRIPTION
**Pull request by IceFloe**
# Pull request checklist

- [x]  I have resolved any merge conflicts. 
- [x]  I have squashed my commits into 1 commit.
- [x]  I have followed the coding style, and reviewed the contributing guidelines. Confirmation: :muscle::sunglasses::facepunch:
- [x]  All tests pass. Demo project builds and runs.

This fixes issue #797 .

# What's in this pull request?

Extend delegate methods for JSQMediaItem. Now you can easily calculate mediaViewSize  base on real layout data.

### CODE REVIEW

**Comment by IceFloe** [comment]
The test testMediaDataProtocol in JSQLocationMediaItemTests was failed because of time, I am not sure why, but sometimes _[snapShotter startWithQueue:]_ takes 3 second, sometimes 40 seconds.

**Comment by jessesquires** [comment]
Thanks @IceFloe ! 😄 

However, this isn't quite the direction that we want to take this.

The media item protocol shouldn't know about `JSQMessageData` or the layout — we want to avoid this coupling. 

For #797 what we want is for media items to provide an aspect ratio, the layout will then use this to find the appropriate size.

**Comment by IceFloe** [comment]
@jessesquires No problem :)

**Comment by jessesquires** [comment]
We'd love other contributions though! 😄 

Any help for the 7.2.1 milestone would be great! 

https://github.com/jessesquires/JSQMessagesViewController/milestones/7.2.1

**Comment by IceFloe** [comment]
I will try to help you guys :)

**Pull request closed without merging**
