### PR TITLE
Allow users to create their own views inside message bubbles.

### PR DESCRIPTION
**Pull request by ryangrimm**
## Pull request checklist
- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: **:muscle::sunglasses::facepunch:**
## What's in this pull request?

The JSQCustomMediaItem class is the starting place for allowing users to
create their own custom views. It manages the communication between the
cell/collection view and the custom view.

The JSQCustomMediaView is the foundation for all custom views. Any
custom view either needs to use an instance of this class and add their
own viewes to it or subclass it.

The JSQHTMLMessageView is a subclass of JSQCustomMediaView and allows
HTML to be displayed inside a message bubble. As a nice bonus, the default font and text color for the HTML is fully managed for the user.

Basic unit tests as well as enhancements to the demo are included.

simulator screen shot apr 10 2016 1 45 37 pm

### CODE REVIEW

**Comment by eliburke** [comment]
@ryangrimm this is great. Very nicely done!

**Comment by jessesquires** [comment]
At a glance, :+1: :tada: 

Thanks for working on this @ryangrimm !

Mind rebasing / resolving conflicts?

**Comment by ryangrimm** [comment]
@jessesquires thanks! Don't mind rebasing and resolving conflicts at all. Will try to get around to it in the next couple hours or so.

**Comment by CavalcanteLeo** [comment]
UHUUUUUUU

**Comment by ryangrimm** [comment]
@jessesquires and @eliburke, I got the conflicts resolved and my branch updated with the latest from develop.

**Comment by MacMeDan** [comment]
@eliburke it looks like there are conflicts with this again 😥

**Comment by ryangrimm** [comment]
I'm happy to resolve the conflicts again. @jessesquires have any idea on what it would take to get the pull request accepted so I don't have to resolve conflicts too often?

**Comment by MacMeDan** [comment]
Ya I'm also having the same issue.

**Comment by jessesquires** [comment]
@ryangrimm -- ha 😅 i'm sorry! Actually, maybe hold off for now. After the 7.x release, I'll be merging stuff like crazy.

I'll ping you again when I'm ready to merge if that's ok! 😄

**Comment by TheRyanHickman** [comment]
epic Epic EPIC!

**Comment by ilin-in** [comment]
When you rotate device multiple times it increasing the size of cell

**Comment by ilin-in** [comment]
Better to have params thats specify is that message relates to system or user

**Comment by kmpnz** [comment]
What is the status of this pull request? Will this ever get merged?

**Comment by kmpnz** [comment]
@jessesquires @ryangrimm I've re-applied all the changes from original @ryangrimm pull request on top of current `develop`, cause fixing the all the merge conflicts was quite tedious. I've also fixed the issue @ilin-in mentioned:
> When you rotate device multiple times it increasing the size of cell

Let me know what you guys think. Would be nice to merge it

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Pull request closed without merging**
