### PR TITLE
ImageOptim on assets

### PR DESCRIPTION
**Pull request by jstart**
## What's in this pull request?

Simple change, ran ImageOptim (https://imageoptim.com) on all assets included in the project.  I regularly do this on projects before deploying to the App Store.

### CODE REVIEW

**Comment by Lucashuang0802** [comment]
@jstart @jessesquires It's good to keep it small. I will vote for it. Can you give me some numbers of the shrinking size? Besides, should you go to `develop` branch rather than `master`?

**Comment by jstart** [comment]
@Lucashuang0802 I submitted to master in case there was a plan to do another minor 7.x release.  If all development is going to 8.x I'll submit to develop.

**Comment by jessesquires** [comment]
Thanks @jstart !

I usually run this too, before committing, but might have missed some of these. Thanks!

Sorry for the delay -- I've been catching up after some time off. 😄 

Thanks @Lucashuang0802 !

**Comment by jessesquires** [comment]
Oops. Merged to master. No worries. I'll sync the branches.

**Pull request merged**
