### PR TITLE
Fixed a warning

### PR DESCRIPTION
**Pull request by priteshshah1983**

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @priteshshah1983 - but this is a fix for Xcode 7. See 7b2b2381539e3443de4fd066bd0f97b394352a79. I recommend using the Xcode 7 beta.

**Comment by priteshshah1983** [comment]
I saw this warning on ````Xcode Version 6.4 (6E35b)```` if that helps.

**Comment by priteshshah1983** [comment]
My bad! I get it now. Sorry wasn't reading :)

**Comment by jessesquires** [comment]
All good! :smile:

**Pull request closed without merging**
