### PR TITLE
Add settings and tailess bubble

### PR DESCRIPTION
**Pull request by MacMeDan**
## Pull request checklist

- [X] All tests pass. Demo project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: :muscle::sunglasses::facepunch:

## What's in this pull request?

>Update to Swift Example project. Adding a new landing page with a new Settings page. Currently has setting for adding and removing bubble tails. Cleaned up unused code and added comments.

### CODE REVIEW

**Comment by jessesquires** [comment]
we should get the swift example building on travis-ci, too

**Comment by jessesquires** [comment]
mind squashing and rebasing on develop? looks like this branch is out-of-date 😄

**Comment by MacMeDan** [comment]
@jessesquires Ya

**Comment by MacMeDan** [comment]
This has been updated 👊

**Comment by jessesquires** [comment]
hey @MacMeDan -- there's *a lot* of unrelated commits here. https://github.com/jessesquires/JSQMessagesViewController/pull/1582/commits

maybe try closing this and re-opening a fresh PR?

**Comment by MacMeDan** [comment]
Sorry I must still not have squashing working right.

**Pull request closed without merging**
