### PR TITLE
Fix #1063, replaced keyboardController with inputAccessoryView

### LINKED ISSUE #1063: Keyboard handling in iOS 9 has changed, keyboard controller no longer needed
Hi Jesse,

As described in another issue that has been closed for some reason, the keyboard controller is not working correctly in iOS 9 betas. The issue seems to be from the keyboard controller attempting to access private view hierarchy which is no longer correct on iOS 9.

The correct design is to have the input accessory view on the controller itself, rather trying to place it by listening to frame changes. Let the system take care of it. This is how the messages app implements it. Keyboard dismiss should be done through `UIScrollView`'s `keyboardDismissMode`.

The entire premise of "keyboard controlling" is misguided, as on iOS, an application has little control of the keyboard. And it seems this mistake has been made by virtually all the messages applications as evident by the same looking bug on iOS 9.

I opened a similar issue in the past and it was dismissed as low priority because it was just related to how the input accessory view moved differently in relation to the keyboard. Now the issue is acute with iOS 9. I was half way implementing this, but I am now working on other things and will only be able to assist here and there.

Thanks,
Leo

### PR DESCRIPTION
**Pull request by kirualex**
## Pull request checklist

- [X] All tests pass. Demo project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have squashed my commits into 1 commit.
- [X] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: :muscle::sunglasses::facepunch:

## What's in this pull request?
Replaced keyboard controller with proper inputAccessoryView and constraints handling.

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @kirualex !

I'll merge this once 7.2.1 is closer to completion! :smile:

**Comment by jessesquires** [comment]
derp. this shouldn't have been closed. it was closed automatically by deleting the `release_8.0` after merging to develop. re-opening.

**Comment by jessesquires** [comment]
hey @kirualex -- do you still want to support this PR? 😄 

if so, do you mind resolving conflicts? then i'll be happy to merge!

**Comment by jessesquires** [comment]
merged manually

**Comment by JeffModMed** [comment]
Hello, my company needs a fix for the hardware keyboard bug asap, so I was considering using the develop branch as a submodule instead of the latest release. I'm not familiar on if/when you guys do QA or anything similar, but I see you guys are halfway through development of 8.0.0. Would you consider it safe to use develop at this point? Or am I risking introducing a lot of bugs into my project? Thanks

**Comment by jessesquires** [comment]
Hey @JeffModMed ! 😄 

I definitely would not use develop right now 😅

**Comment by JeffModMed** [comment]
Hi @jessesquires :) 
Thanks for replying. Can you point me to a place in the code from the latest release where I might be  able to apply a quick fix for this? I'm assuming it's somewhere in that keyboard controller class that's  currently in there?

**Comment by jessesquires** [comment]
Hey @JeffModMed -- probably best to fork the repo, apply this patch yourself, then fixup anything else that breaks 😄

**Pull request merged**
