### PR TITLE
add video thumbnail support

### PR DESCRIPTION
**Pull request by weekwood**
#628

### CODE REVIEW

**Comment by jessesquires** [comment]
thanks @weekwood - i'll look soon!

**Comment by StormFactory** [comment]
Hi guys. I tested out the video thumbnail code and adding it works with pulling up the video thumbnails.  The bad part is it destroys the load time of the chat room and makes the room lag until, I'm guessing the loading is complete.  I'm not sure, but that makes me think this is happening synchronously instead of asynchronously.

**Comment by weekwood** [comment]
@StormFactory thanks let me test will big video and device

**Comment by weekwood** [comment]
@StormFactory I changed synchronously to asynchronously, please feel free to review it.

**Comment by StormFactory** [comment]
@weekwood I tried to fix the issue with adding a dispatch_async to the thumbnailImage method, but I'm not as skilled with that so I kept getting errors.  I just tested your asynchronous commit and it loaded without any lag.  With that said, the previews only seem to show after you scroll away.  Once they do show, they show multiple frames in the thumbnail.  Here's an image to show you what I mean.
img_1625

**Comment by weekwood** [comment]
@StormFactory look like the thumbnail size is too small.  let me change the fit method

**Comment by StormFactory** [comment]
@weekwood Here's a video example of what's happening with the thumbnails not loading until you scroll away and scroll back to them. https://vimeo.com/115841044

**Comment by weekwood** [comment]
@StormFactory I added one more UIImageView to fix this, if you have any idea use
```
[UIColor colorWithPatternImage:self.thumbnailImage]
``` 
to fix it, let me know.

**Comment by weekwood** [comment]
@jessesquires any idea to refresh the cell after generate the thumbnail?

**Comment by Lucashuang0802** [comment]
Duplicate with #1408?

**Comment by jessesquires** [comment]
@Lucashuang0802 - not exactly. they both have pros/cons and i'd like to incorporate ideas from both. 

namely:

1. The API for setting a thumbnail should be simple, like in #1408 
2. This changeset introduces too much complexity / dependencies by using `AVAssetImageGenerator` internally. 

So, we should do (1) and then provide a new VideoThumbnailFactory object that clients can use to generate a thumbnail, using the ideas from this PR.

**Comment by jessesquires** [comment]
Thanks @weekwood !

We included your changes in #1823

**Comment by weekwood** [comment]
@jessesquires Great

**Pull request closed without merging**
