### PR TITLE
Fixed issue with bottom offset when Tab Bar is transparent

### PR DESCRIPTION
**Pull request by evfemist**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____

## What's in this pull request?
If I embed JSQMessagesViewController in UITabBarController - then toolbar not visible
>...

### CODE REVIEW

**Comment by jessesquires** [comment]
nice! thanks @evfemist !

**Comment by jessesquires** [comment]
This fixes #179, correct?

**Comment by evfemist** [comment]
Not sure, cause in my case it was issue only when tab bar transparent

**Comment by jessesquires** [comment]
thanks @evfemist ! 🎉

**Comment by sebastianludwig** [comment]
@evfemist your PR has been reverted in #1623. Would you mind opening a new issue to keep track of your issue?

**Pull request merged**
