### PR TITLE
#1322 Use @import JSQSystemSoundPlayer; and use_frameworks! in Podfile. 

### PR DESCRIPTION
**Pull request by marco1981**
```pod install``` executed using latest cocoapods version (0.39.0)

### CODE REVIEW

**Comment by jessesquires** [comment]
thanks @marco1981 !

Looks like the same change as #1284, but with some unrelated changes. Not sure we need "use_frameworks!"

**Comment by harlanhaskins** [comment]
Won't this break iOS 7 support?

**Comment by jessesquires** [comment]
Ah good catch. The module import should be fine, but `use_frameworks!` isn't good for the example project.

**Comment by marco1981** [comment]
We'll not be able to insert ```@import JSQSystemSoundPlayer;``` if we don't add ```use_frameworks!``` in Podfile and it will not be possible to add JSQMessages pod as a dependency of a Swift Pod. I don't know if you can consider to create a special release ( including this changes ) that supports only iOS8 and above

**Comment by jessesquires** [comment]
@marco1981 I'm in the process of planning the 8.0 release of the library, which will drop iOS 7 support. :smile:

**Comment by marco1981** [comment]
:thumbsup:

**Comment by MacMeDan** [comment]
So should we close this issue?

**Comment by jessesquires** [comment]
@MacMeDan :+1: 

closing in favor of #1322

**Comment by jessesquires** [comment]
oops. also #1284

**Pull request closed without merging**
