### PR TITLE
add audio message to swift sample app

### PR DESCRIPTION
**Pull request by Lucashuang0802**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: Lucashuang0802

## What's in this pull request?

> This includes the codes for adding audio messages to the swift sample app. It seems like #1608 has a wrong checklist. The audio message was checked but not there. I think photo message is done. 😄

### CODE REVIEW

**Comment by Lucashuang0802** [comment]
@MacMeDan

**Comment by jessesquires** [comment]
Thanks @Lucashuang0802 ! 👍 

Looks good. 1 comment:

Let's remove `SwiftExample/SwiftExample/jsq_messages_sample.m4a` and just reference whatever is in the original demo project. (As in, when you "add to Xcode project", don't copy the file)

**Comment by MacMeDan** [comment]
I second the motion. Similar to how we are doing images for avatars. 🃂

**Comment by Lucashuang0802** [comment]
@jessesquires done with update the reference and rebase to `jessesquires:develop`

**Comment by Lucashuang0802** [comment]
07fc2ff adds the handle of downloading. It seems to be okay now. I will be working on the front page.

**Comment by jessesquires** [comment]
thanks @Lucashuang0802 !

**Pull request merged**
