### PR TITLE
change the Queue in MKMapSnapshotter to dispatch_get_main_queue()

### PR DESCRIPTION
**Pull request by AndriyBas**
The reason: inside completion block UIKit classes (MKPinAnnotationView) were created. That usually stopped animations in all the application (the same effect as to call “UIView.setAnimationsEnabled(false)”)
Reproduce: send a lot of Location Items, and enter/exit the chat with that locations 3-5 times

## Pull request checklist

- [x] All tests pass. 
- [x] Demo project builds and runs.
- [x] I have resolved merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines). 

[Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____

### CODE REVIEW

**Comment by AndriyBas** [comment]
thanks @Cocoanetics for helping detect the bug with:  https://github.com/Cocoanetics/DTFoundation/blob/develop/Core/Source/iOS/Debug/UIView%2BDTDebug.h

**Comment by AndriyBas** [comment]
Resolves issue https://github.com/jessesquires/JSQMessagesViewController/issues/1632

**Comment by jessesquires** [comment]
Thanks @AndriyBas !

So.. shouldn't the entire `completionBlock` here just be dispatched on the main queue?

**Comment by AndriyBas** [comment]
@jessesquires you're right, thanks for an advice. Updated the PR to dispatch entire “completionHandler” on the main queue and run snapshotter work on the background thread. 
Plz, review changes.

**Comment by AndriyBas** [comment]
@jessesquires btw, on my side the test `testMediaDataProtocol` succeeds, not sure why it failed on Travis CI. Probably travis machine is not fast enough.

**Comment by AndriyBas** [comment]
@jessesquires now it passed, seems like that was Travis bug.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Pull request closed without merging**
