### PR TITLE
Issue 1382 typing indicator animated

### PR DESCRIPTION
**Pull request by fishstix-medhelp**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: __ :muscle::sunglasses::facepunch:__

## What's in this pull request?

Adding a configurable property to JSQMessagesViewController controlling whether the typing indicator gets the new animated behavior. Default is NO, adhearing to previous behavior.
Updating Unit Tests to assert default "NO" values

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @fishstix-medhelp ! :smile: Looks like a lot of unrelated commits here, too. Mind squashing into 1 commit?

**Comment by jessesquires** [comment]
Friendly ping @fishstix-medhelp :smile:

**Comment by fishstix-medhelp** [comment]
My merge with release didn't go as smooth as I wanted.  Hopefully this rebase went ok....

**Comment by jessesquires** [comment]
hey @fishstix-medhelp 😄 

looks like there's still some conflicts and a lot of unrelated commits. 😅  you can check here: https://github.com/jessesquires/JSQMessagesViewController/pull/1524/commits

normally i wouldn't mind about rebasing, but with all of the unrelated commits, it makes it difficult to see what **your** actual changes are to review.

sometimes it's easier to open a new PR. let me know what works for you! 👍

**Pull request closed without merging**
