### PR TITLE
Update apps_using_this_library.md

### PR DESCRIPTION
**Pull request by MichaelDanielTom**
## Pull request checklist

- [ ] All tests pass. Demo project builds and runs.
- [ ] I have resolved any merge conflicts.
- [ ] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____

## What's in this pull request?

>...

### CODE REVIEW

**Comment by jessesquires** [comment]
thanks @MichaelDanielTom !

**Comment by MichaelDanielTom** [comment]
@jessesquires Thanks so much for creating this great library... I'm currently implementing the same thing in Android and wish I had this :)

**Comment by jessesquires** [comment]
@MichaelDanielTom -- would you be interested in collaborating on this?

Is your goal to basically have a direct android port?

I started https://github.com/MessageKit for a Swift re-write of JSQMessages. (Haven't started yet.) But, we could add a repo for android and I could add you to the organization...

what do you think?

**Comment by MichaelDanielTom** [comment]
@jessesquires Right now we're making the android app in react-native (primarily for android, with the hopes of backporting it to iOS in a few months). I think I spoke a little too soon as I haven't realllllly started implementing much stuff, but we're planning on using [gifted messenger](https://github.com/FaridSafi/react-native-gifted-messenger). 

As an aside, I did implement the side side swipeable timestamps for cells for the obj-c version. It's a tad hacky, but I definitely want to clean it up submit a pull request to put it in the main library once the Android app is done! We promised some of our partners that we'd have an android app out by May 31, and it still has has a little ways to go, so I probably won't have too much time in the next 2 weeks, but after that I'll definitely clean it up!

**Pull request merged**
