### PR TITLE
Fix crash on delete pressed for JSQMessagesComposerTextView

### PR DESCRIPTION
**Pull request by GianniCarlo**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊

## What's in this pull request?
Fixes the crash on delete menu button pressed

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @GianniCarlo ! 👍

**Comment by jessesquires** [comment]
Hm, after looking at iMessage, `delete` isn't even an option. 

I think we should remove `delete:` altogether from the menu.

**Comment by jessesquires** [comment]
In fact, shouldn't we just call `super` in `canPerformAction: withSender:` ?

**Comment by GianniCarlo** [comment]
you are right @jessesquires , if we remove the `canPerformAction: withSender:` from the `JSQMessagesComposerTextView` the actions listed are the default plus there's a custom action registered for the demo. As it is now it won't show that custom action

**Comment by GianniCarlo** [comment]
Updated pull request

**Comment by jessesquires** [comment]
Here's what I'm suggesting:

```objective-c
- (BOOL)canPerformAction:(SEL)action withSender:(id)sender {	
    [UIMenuController sharedMenuController].menuItems = nil;
    return [super canPerformAction:action withSender:sender];
}
```

wouldn't this fix the crash and keep the fix from #1281?

**Comment by GianniCarlo** [comment]
oooh, hadn't seen that issue, yup then the function is indeed needed, I'll update it now

**Comment by GianniCarlo** [comment]
updated 👍

**Comment by jessesquires** [comment]
Awesome. So this fixes the crash, and still fixes #1281?

**Comment by GianniCarlo** [comment]
yes, fixes the crash as the default list of actions doesn't include the action `delete`. And `[UIMenuController sharedMenuController].menuItems = nil;` takes care of #1281

**Comment by jessesquires** [comment]
Thanks so much for jumping on this so quickly @GianniCarlo ! 🎉

**Comment by jessesquires** [comment]
cherry-picked into `release_7.3`

**Pull request merged**
