### PR TITLE
Add outgoing image support to Swift demo

### PR DESCRIPTION
**Pull request by GianniCarlo**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊

## What's in this pull request?
This adds support for sending images using `didPressAccessoryButton` in the Swift demo. I also tweaked `didPressSendButton` so it has the same comments as the Objective C demo.

@MacMeDan my plan is to add support for each media in its outgoing form in a pull request. Then I'll do a pull request for the simulation of incoming messages of every type of message. Is that ok? or should I split the incoming messages pull request too? let me know what you think

### CODE REVIEW

**Comment by MacMeDan** [comment]
@GianniCarlo I think it will be fine to have them together.

**Comment by MacMeDan** [comment]
We will also want to add tests for this stuff to prevent breaking in the future. If you want to add that to the features in the pull requests I think it would be best practice.

**Comment by GianniCarlo** [comment]
Got it, I'll add it later tonight

**Comment by jessesquires** [comment]
We should avoid adding images twice, if possible 😓 

Maybe the 2 projects can share an asset catalog?

**Comment by GianniCarlo** [comment]
I unified the assets catalog as suggested by @jessesquires . Let me know @MacMeDan when you have the chance to check out the tests I added 👍

**Comment by MacMeDan** [comment]
I'll do it Tuesday morning.

**Comment by MacMeDan** [comment]
@GianniCarlo Things look really good there are just a few issues.
- You need to add this code snippet to the Podfile so that tests will work. 
` target 'SwiftExampleTests' do
    pod 'JSQMessagesViewController'
end `

Then lets go ahead and remove the SwiftExampleTests because it is not actually testing anything.

Other then that this looks great. Great work 👻

**Comment by GianniCarlo** [comment]
Great! already updated with your suggestions @MacMeDan  👍👍👍 I'll get right on the other items in the checklist throughout this week

**Comment by MacMeDan** [comment]
Sounds great. @jessesquires will get this merged when he has time. But all looks good to me. Keep Up the good work.  🤘

**Comment by jessesquires** [comment]
1 last thing. sorry 😅 

Let's go ahead and remove: 

- `AppIconSwift.appiconset` and just use the existing AppIcon from the ObjC demo
- `NiceSelfi.pdf` because I just realized this is > 2 MB 😱 (sorry @MacMeDan ! nothing against your face! 😆)

This repo is getting quite large 😅

**Comment by GianniCarlo** [comment]
Done @jessesquires 👍

**Comment by MacMeDan** [comment]
I disagree with those suggestions 😡 but ok.

**Comment by MacMeDan** [comment]
Got to have that high Rez so I look good on anything 😁

**Comment by jessesquires** [comment]
Thanks guys! 🎉

**Pull request merged**
