### PR TITLE
Offset the view based on the height of the Navigation bar.

### PR DESCRIPTION
**Pull request by MacMeDan**
## Pull request checklist
- [X] All tests pass. Demo project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊
## What's in this pull request?

   Just a fix for offsetting the view based on the Navigation-bar when presented via a push. 
Does not effect when presenting as root view in a NavigationController.✅

### CODE REVIEW

**Comment by Lucashuang0802** [comment]
I still found the same issue running on iPhone6 Plus with iOS 9.0.

**Comment by MacMeDan** [comment]
I will take a look thanks @Lucashuang0802.

**Comment by jessesquires** [comment]
Usually you don't want `navigationBar.frame`, but `self.topLayoutGuide.length`

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Pull request closed without merging**
