### PR TITLE
Attributed text messages

### PR DESCRIPTION
**Pull request by flavionegrao**
Hey, I've seen few requests(#1052, #520, ...) for adding attributed strings to the text bubbles.
I have implemented it, however don't know I was able to meet your coding style standards.
Hope it helps somehow, cheers 
ios simulator screen shot 29 06 2015 6 16 47 pm

Flavio

### CODE REVIEW

**Comment by Luke47** [comment]
Thank you Flavio! Awesome job :)

**Comment by BesatZardosht** [comment]
when I add JSQAttributedMessage it mess everything up..
the scroll does not work correctly and some of my JSQMessages change too!
I really like the idea but this does not work for me

**Comment by ravitejaobelisk** [comment]
Hi Flavio, thanks for the implementation. I've merged your additions to v7.2.0 and everything is working perfect. Many thanks :)

**Comment by vishalgabani** [comment]
Thanks a lot @flavionegrao. It helped me lot to show attributed text on chat view. :smile:

**Comment by rkittinger** [comment]
We have animated smilies in our app and would like to attach these in messages, however NSTextAttachment does not animate the image. Would this be possible with this framework? How would you suggest implementing this?

**Comment by lww** [comment]
What happened to this? I would need attributed text too... What is the official recommended way of using it, or do I have to merge it myself.

It would be very nice to have that in the core project.

**Comment by jessesquires** [comment]
Hi all. This is coming in `v8.0` of the library. (see #572)

Very sorry this PR died. At the time, this was too big of a change to accept, and now there's been many changes since this was originally opened.

**Pull request closed without merging**
