### PR TITLE
Add SnipSnap to the list of apps that use this

### PR DESCRIPTION
**Pull request by atroutt**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪 😎  👊

## What's in this pull request?

Add SnipSnap to the list of apps that use this

SnipSnap uses JSQMessagesViewController for both the Scout feature (a deal concierge service that can help you save money on anything) and on our live support chat.

### CODE REVIEW

**Comment by atroutt** [comment]
Shameless plug, we needed something similar for SnipSnap Android, so we are releasing https://github.com/snipsnap/SlyceMessaging. It's nowhere near as sophisticated and amazing as JSQMessagesViewController yet, but it works and we will continue to improve it over time.

**Comment by jessesquires** [comment]
Awesome! Thanks @atroutt ! 🎉

**Comment by jessesquires** [comment]
@atroutt - We're planning on re-writing this library in Swift, soon. https://github.com/MessageKit

Another big change is moving to a GitHub Organization — to facilitate more contributions, and have better organization/visibility of sub-projects. Another thing on my road map was an Android port project `MessageKit/MessageKit-Android`.

Would SnipSnap be interested in joining forces? 😊

**Comment by atroutt** [comment]
@jessesquires yes! definitely. This is my last week at SnipSnap, but I'm not going to lose touch with my fellow Android devs here. Count me in for Android!

**Comment by jessesquires** [comment]
@atroutt awesome! 🎉

**Comment by atroutt** [comment]
@jessesquires my Android dream team also includes @jchunchar (SnipSnap Lead Android Dev who wrote the original code) and @MatthewPageCS (summer intern and student at Purdue who did the librification of John's code) who helped make SlyceMessaging possible.

**Comment by jessesquires** [comment]
@atroutt 👍 feel free to add them to MessageKit if they are interested in helping out 😊 (you should have permissions to add them to the Android Team)

**Pull request merged**
