### PR TITLE
Add check for Object_replacement_character

### PR DESCRIPTION
**Pull request by azonov**
https://github.com/jessesquires/JSQMessagesViewController/issues/1323 fixed

### CODE REVIEW

**Comment by marco1981** [comment]
I saw you had this error in your CI: "The command "brew update" failed and exited with 1 during ."
Since I had the same issue, you need to add a workaround to cope with this issue in Homebrew: 
https://github.com/marco1981/JSQMessagesViewController/commit/3e718c1022b97e1a90b1fe4c1e52880bf3d85937

Basically you need to change line 23 in .travis.yml:
```brew update || brew update```

**Comment by jessesquires** [comment]
Hey @azonov ! :smile: 

Sorry it took so long to answer here. Are you still interested in supporting this PR?

**Comment by jessesquires** [comment]
Hey @azonov - one last ping before we close this and manually apply the fix.

Can you resolve conflicts and update the PR?

Also, there's a bunch of unrelated work here, right? We only want the changes in `NSString+JSQMessages.m`, correct?

>// cc @eliburke

**Comment by azonov** [comment]
We only want the changes in NSString+JSQMessages.m, correct – yes
Can you resolve conflicts and update the PR? - after weekends
Thanks,

Andrey Zonov
________________________________
Senior iOS Developer
DataArt<http://www.dataart.ru/>


<https://htmlsig.com/skype?username=andry-zonov>
skype:  <https://htmlsig.com/skype?username=andry-zonov> andry-zonov
Andrey.Zonov@dataart.com

**Comment by jessesquires** [comment]
thanks @azonov !

sometimes it's easier to just submit a new PR. let me know if that works better for you 😄

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Pull request closed without merging**
