### PR TITLE
Added HTML Media Message Type

### PR DESCRIPTION
**Pull request by Stunner**
Handy for rendering things such as equations/LaTeX easily. Made for use within [GotIt!](https://itunes.apple.com/us/app/gotit!-instant-study-help/id797535508?mt=8). Sample HTML media type added to sample project.

### CODE REVIEW

**Comment by dmyers** [comment]
This looks pretty sweet for HTML rendering. Is it performant? What do you think @jessesquires. Maybe get the merge conflict fixed and it could be added @Stunner?

**Comment by Stunner** [comment]
@dmyers Done.

**Comment by dmyers** [comment]
:+1: Sweet. What do you think @jessesquires?

**Comment by dmyers** [comment]
I did some testing on this and it works really well. Is there a way to style the fonts by chance @Stunner?

**Comment by Stunner** [comment]
@dmyers Didn't get the chance to implement that, was going to take more time than we had allocated for that sprint. I wouldn't mind revisiting it but am unsure when I'll be free to dedicate time to it (pretty swamped these days). Would greatly appreciate any assistance.

**Comment by dmyers** [comment]
:+1: Sweet. What do you think @jessesquires? I'm not exactly sure on that myself @Stunner, I'll try to play around with it some more though.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Pull request closed without merging**
