### PR TITLE
Fix issue #1063, replaced keyboard controller with proper inputAccess…

### PR DESCRIPTION
**Pull request by kirualex**
## Pull request checklist

- [X] All tests pass. Demo project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have squashed my commits into 1 commit.
- [X] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: :muscle::sunglasses::facepunch:

## What's in this pull request?
Replaced keyboard controller with proper inputAccessoryView and constraints handling.

### CODE REVIEW

**Comment by jessesquires** [comment]
Hey @kirualex ! This is awesome! :tada: :smile: 

At a glance, this looks great. A few questions:

- Does with work with iOS 7?
- Is there anyway we can make this a non-breaking change? (Currently this will have to included in v8.0 of the library because there are major API changes)

**Comment by kirualex** [comment]
Hi @jessesquires, sorry for the late response. 
- I didn't have the opportunity to test on IOS 7, so not sure about wether it will work. If someone can try with an older device it would be great.
- As you may have seen, this commit removes a lot more lines than it adds, which makes me think it might be best to keep it as a "clean restart" for v8.0. Making it non-breakable would be quite a headache I think!

**Comment by jessesquires** [comment]
>Making it non-breakable would be quite a headache I think!

Sounds good! :smile: 

Do you mind updating the PR to merge into the `8.0_release` branch instead of `develop` ?

**Comment by jessesquires** [comment]
replaced by #1529

**Pull request closed without merging**
