### PR TITLE
Smooth scrolling! 

### PR DESCRIPTION
**Pull request by galambalazs**
I made scrolling perfect on my iPhone 5s **without removing auto-layout**.

I commented on every commit.

Basically the changes in order of their importance:
- `textView.scrollEnabled=NO` causes scrolling problems for some reason, but it can be safely disabled because the layout takes care of that
-  `NSDateFormatter` optimized by having separate Date & Time formatters and not changing the style of a single formatter all the time.
- make sure we don’t cause unnecessary work with `setText=nil` upon cell reuse 
- remove forced rasterization to unburden the CPU
- move default dataDetector setting to `textView.awakeFromNib` instead of `cellForRowAtIndexPath` so library users can have better control

The biggest bottleneck left seems to be `dataDetectors` as they heavily block the main thread.

When _testing_ this PR I advise you to **disable** them to see the smoothness achieved by these commits (without being affected by dataDetectors).

Maybe later I’ll come up with something to make that part faster as well.

### CODE REVIEW

**Comment by galambalazs** [comment]
Combined with TTTAttributedLabel (which has way faster rendering and does data detection on a background thread) I managed to eliminate ALL jankiness. Seriouosly, it flies.

I think it's a good call to switch to that for 8.0

**Comment by galambalazs** [comment]
Just opened a PR for TTTAttributedLabel that will make it fly even more with data detectors.

Just look at these number UITextView (1.662s) vs TTT (0.084s).

datadetector

**Comment by jessesquires** [comment]
thanks @galambalazs!

wow - `UITextView` :cry:

**Comment by galambalazs** [comment]
Good news:

I managed to implement a version of TTTLabel which allows the native data detector actions to appear.
(Currently you'd have to implement them yourself, plus localize etc...)


Jesse: there are two quick demo projects and two videos in the smooth scrolling issue thread.
Please do take a look at the performance characteristics show in those.

i'm now 100% sure TTT is the way to go.


I'll probably break this PR up to separate small ones and 1-2 may be merged so 7.x branch gets somewhat faster. But 8.0 is TTT all the way.

**Comment by thiemdv** [comment]
Thank you @galambalazs 
It works like a charm.

**Comment by benjaminhallock** [comment]
I've taken some of these quick fixes and tried to apply to my project. I would really like to see this go somewhere....

**Comment by galambalazs** [comment]
Still waiting for @jessesquires to decide what's the plan for 8.0

The biggest change would come from switching to TTTAttributedLabel

In that case, only the date formatter is relevant from here.

Maybe I'll add a separate PR for that's easy to merge.

**Comment by benjaminhallock** [comment]
Also you had a `SPViewController`  that was one error, couldn't get it to work in my project either.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Pull request closed without merging**
