### PR TITLE
A fix for #1268

### PR DESCRIPTION
**Pull request by Lucashuang0802**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: @Lucashuang0802

## What's in this pull request?

The OP indicated that the `contentInset` gets reset when keyboard shows/dismisses. It turns out that the `jsq_setCollectionViewInsetsTopValue` did not include it.

### CODE REVIEW

**Comment by Lucashuang0802** [comment]
I was thinking why there are so many commit but one file change which is desired. Because you use the git squash instead. lol. Do you consider this as a bug? lol

**Comment by Lucashuang0802** [comment]
Base branch is updated.

**Comment by jessesquires** [comment]
Thanks @Lucashuang0802 !

Looks like there's a lot of unrelated commits here. Want to close this and re-open a fresh PR?

**Comment by Lucashuang0802** [comment]
Hmm, I tried to create another PR from my fork `#1268` to `upstream/develop`. Those commits are still included. I'm just wondering what happened or can we use squash commit?

**Comment by Lucashuang0802** [comment]
Let me try to close it first. Because it redirects me to this PR if I create without closing it.

**Comment by Lucashuang0802** [comment]
Do you think you can squash and merge? I will remove my fork `develop`.

**Comment by Lucashuang0802** [comment]
Close because #1713 will handle it, @jessesquires

**Pull request closed without merging**
