### PR TITLE
[Accessibility] Make message view more voiceover friendly

### PR DESCRIPTION
**Pull request by BillCarsonFr**
- Cell is now accessible and will speak sender name and message
- Accessory button has now an accessibility label
- Post announcement when message is received
- Added accessibility label to toolbar’s text view

- Notice : I cannot do all the translation, will need some help

### CODE REVIEW

**Comment by jessesquires** [comment]
thanks @BillCarsonFr ! i'll have a look soon :+1:

**Comment by BillCarsonFr** [comment]
just noticed that i forgot to add the method to configure the cell accessibility in the .h, only updated the .m. I have been doing to much swift :)

**Comment by anamika217** [comment]
Yesterday I got a message that Telegram has been updated to version 3.3.2
In the new version, accessibility feature for sender name is not active. Will it be provided in next update?

**Comment by eliburke** [comment]
@BillCarsonFr can you update your PR? 

@jessesquires This appears to work as advertised. I think it could use improvement, but it's a solid start.

Media cells with interactive behavior (Audio, Video) do not work with voiceover enabled. I think that in order to add that functionality we would need to add a property  to the mediaItem that returns an array of views that JSQMessagesCollectionViewCell can expose via accessabilityElements. We could also add a media type / name property to further differentiate between different cell types. 

I also noticed some differences between how it behaves and how iMessage behaves, but I'm just pointing them out. 
- Does not announce timestamps
- Does not indicate if there are actions available (e.g. long press menu) 
- Announces the local sender's name (iMessage says "Your iMessage")

**Comment by jessesquires** [comment]
@eliburke 👍

**Comment by jessesquires** [comment]
Maybe we can consider more accessibility for v8.0

**Pull request merged**
