### PR TITLE
adds an imageAspect property to JSQPhotoMediaItem

### PR DESCRIPTION
**Pull request by eliburke**
I can re-pull this against 8.0 if you prefer but it should be innocuous as the default keeps existing behavior for mediaViewDisplaySize. 

I forgot that changing the contentMode wasn't actually appropriate as a "Fit" type image with clear background would end up shrinking inside the bubble mask. So this keeps the contentMode as "Fill" and modifies the media size. 

The first image shows default, smallSquare, largeSquare, and the second shows portrait, landscape, and automatic.

screen shot 2016-04-04 at 2 26 48 pm

screen shot 2016-04-04 at 2 27 08 pm

### CODE REVIEW

**Comment by jessesquires** [comment]
Awesome :tada: Love the idea.

1. I'm pretty sure there's an open issue for this. Can we track that down and link here?
2. Small enough change, so we can include in 7.2.1
3. Not a huge fan of the `enum`. Instead of an `enum`, can't we just expose `CGFloat aspect`?

**Comment by eliburke** [comment]
A simple CGFloat value won't do, unless you mean to replace the enum with a bunch of pre-defined static values. Take a look at [mediaViewDisplaySize](https://github.com/jessesquires/JSQMessagesViewController/pull/1522/commits/7e0ec626c2ff952eb97fa6381a3222848cb1404c#diff-12b6c474979f6418ef62a2b556457f0b) and you'll see what I mean-- it's synthesizing a CGSize based on the enum, not just multiplying by a fixed value.

Just noodling here, but an alternative design would be to add a `CGSize customSize` to JSQMediaItem, along with class method(s) to mutate it: 
```
JSQPhotoMediaItem * photoItem = [JSQPhotoMediaItem alloc] initWithImage:image];
photoItem.customSize = CGSizeZero; // default value, defers to JSQMediaItem:mediaSize
photoItem.customSize = [JSQMediaItem automaticSize:image.size];
photoItem.customSize = [JSQMediaItem portraitSize:image.size]; 
photoItem.customSize = [JSQMediaItem portraitSize:CGSizeZero]; 
photoItem.customSize = [JSQMediaItem landscapeSize:CGSizeZero]; 
photoItem.customSize = [JSQMediaItem squareSize:CGSizeZero]; 
```
Anywhere you see CGSizeZero, it uses JSQMediaItem:mediaSize. Or, supply your own value and the class method will mutate as desired. I like that this exposes the aspect ratio calculation to any mediaItem object, but I think it's also more confusing.

**Comment by jessesquires** [comment]
>t's synthesizing a CGSize based on the enum, not just multiplying by a fixed value.

Ahh, I see now. Hm... let's think about this a bit more. I don't want to rush this into 7.2.1, so I've moved it to 8.0.0.

**Comment by jessesquires** [comment]
We should squash commits and rebase this, too :smile:

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Pull request closed without merging**
