### PR TITLE
set number of lines for cellBottomLabel

### PR DESCRIPTION
**Pull request by MacMeDan**
## Pull request checklist

- [X] All tests pass. Demo project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊

## What's in this pull request?

> Default number of lines to 0 so the label adjusts to the text inserted.

### CODE REVIEW

**Comment by jessesquires** [comment]
👍 🎉 

Let's do this for `cellTopLabel` and `messageBubbleTopLabel` too 😄

**Comment by MacMeDan** [comment]
do you want me to add it in this one or new pr.

**Comment by MacMeDan** [comment]
I decided same pr. 🤑

**Comment by jessesquires** [comment]
🎉

**Pull request merged**
