### PR TITLE
swap the bubble tail logic

### PR DESCRIPTION
**Pull request by Lucashuang0802**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: Lucashuang0802

## What's in this pull request?

> It has a minor bug in Swift Example. It's supposed to remove bubble tail when `taillessSettingKey` returns `true`.

### CODE REVIEW

**Comment by MacMeDan** [comment]
What is your reasoning behind this?

**Comment by jessesquires** [comment]
👍

**Comment by Lucashuang0802** [comment]
@MacMeDan I think when `taillessSettingKey` is `true`, it should hide the tail. The app did the other way. 😃

**Comment by MacMeDan** [comment]
Ahh awesome ya just wondering 🤘

**Pull request merged**
