### PR TITLE
Added awesome Implementation of JSQ in swift 🍧

### PR DESCRIPTION
**Pull request by MacMeDan**
## Pull request checklist

- [✅] All tests pass. Demo project builds and runs.
- [✅] I have resolved any merge conflicts.
- [✅] I have squashed my commits into 1 commit.
- [✅] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: :muscle::sunglasses::facepunch:

## What's in this pull request?
An example of JSQMessagesViewController Implemented in Swift along with documentation on how to customize it for yourself.
>...

### CODE REVIEW

**Comment by MacMeDan** [comment]
Apparently it was a problem with my fork which I did not realize 🙃 but I think I have it all figured out now. 🙂

**Comment by jessesquires** [comment]
:tada: 

I'll take a look soon :smile:

**Comment by MacMeDan** [comment]
@jessesquires this codecov looks pretty awesome but I am confused on how to influence it. The first time it ran It said I had increased code coverage by .3% the coverage and then the second time it was 31.6% increase. I assume that is because I merged develop in. How do I get the failing check to pass? 😥 But It does look supper cool. 👾

**Comment by jessesquires** [comment]
@MacMeDan -- yeah the big increase was because of the merge from develop. the current failure is due to a lack of coverage for the new code, I think.

So, this PR is quite large. How about we do the following:

1. Close this.
2. Resubmit with *very* small PRs to do this incrementally. For example, 1 PR just to add an empty project, another to add an empty view controller, etc.

How's that sound to you? 

Also, sorry for not reviewing sooner! 😅 This isn't the highest priority right now, but once the last 7.x is out, things will move faster. 😁

**Comment by MacMeDan** [comment]
@jessesquires I am ok with doing that it just seems contradictory to squashing them all together. 😏 But Ya I am fine with doing small pull requests I will do that for now on.

**Comment by kurko** [comment]
Yeah, it's virtually impossible to review a 10k LoC PR

**Pull request closed without merging**
