### PR TITLE
Improved paste support for images

### PR DESCRIPTION
**Pull request by eliburke**
@jessesquires This PR got a little bit bigger than expected, but it revamps the Demo project to be a little more useful (images are resized and added as attachments, and text+images are now sent when pressing the Send button). I'm not 100% happy with the updated protocol and the attributedString handling so critique is welcome.
## What's in this pull request?

Update JSQMessagesComposerTextView protocol to expose canPerformAction
Added NSTextAttachment subclass to contain original data alongside thumbnail
Add NSAttributedString category for listing attachments
Add UIImage category for resizing images
Update demo project to support image paste and attachment handling
## Some emojis:

👍🎉😜

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks for working on this! :+1: 

- What are the related issues here?
- Can you explain the UI/UX changes here or post a gif?

**Comment by eliburke** [comment]
The primary issue is #1407, but also #1345 

There are two facets to the PR. One updates JSQMessagesComposerTextView to expose canPerformAction. This is called to determine if the Paste menu should appear when the pasteboard contains an image. (alternatively, it is possible to implement paste: in JSQMessagesViewController, but if we use that design, it is binary... implement paste:, and "Paste" will always be added to the context menu)

The second part of the PR updates the demo with an improved implementation of image paste. The previous version was coded to send a message as soon as it was pasted. The new version adds images as attachments in the text view. When you click send, it creates one message with all of the text, and then N additional messages for each image attachment. 

If someone implements a combined "image + text" format, they can modify the technique used in the demo app to create mixed-media combo cells. 

apr 05 2016 10 48

**Comment by jessesquires** [comment]
That gif looks awesome :tada: 

This will definitely have to go in 8.0. 

We'll also be switching to `NSAttributedString` for text messages instead of `NSString` for 8.0, so we should coordinate those changes. Hopefully it will make everything pretty simple

**Comment by eliburke** [comment]
If you ever need to make an animated gif, there's a great app in the Mac App Store called GIF Grabber.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Pull request closed without merging**
