### PR TITLE
Add Support for RTL languages and update the Demo project with Hebrew…

### PR DESCRIPTION
**Pull request by GuyKahlon**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have squashed my commits into 1 commit.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____

## What's in this pull request?

Add Support for RTL languages and update the Demo project with Hebrew for demonstrate.

The main change is pretty simple, in JSQMessagesBubbleImageFactory.m file I add a Boolean property isRightToLeftLanguage.
I flipped for Incoming bubble depend on the language direction.

```objective-c
- (JSQMessagesBubbleImage *)outgoingMessagesBubbleImageWithColor:(UIColor *)color
{
+ return [self jsq_messagesBubbleImageWithColor:color flippedForIncoming:NO ^ self.isRightToLeftLanguage];
}

- (JSQMessagesBubbleImage *)incomingMessagesBubbleImageWithColor:(UIColor *)color
{
+ return [self jsq_messagesBubbleImageWithColor:color flippedForIncoming:YES ^ self.isRightToLeftLanguage];
}
```

Update the TextView.textAlignment property to natural in JSQMessagesCollectionViewCellIncoming and JSQMessagesCollectionViewCellOutgoing xib files.

Update Unit Tests after RTL support (The tests were failed only in device with RTL language.).

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks so much for working on this @GuyKahlon ! :tada: 

Please resolve your conflicts and I'll have more feedback soon :smile:

**Comment by GuyKahlon** [comment]
Hey @jessesquires all conflicts have been resolved 😎.

**Comment by jessesquires** [comment]
Thanks! @GuyKahlon! 

Looks like GitHub is still saying there are conflicts :sweat_smile:

**Comment by GuyKahlon** [comment]
@jessesquires Is it okay now?

**Comment by jessesquires** [comment]
@GuyKahlon :+1: Conflicts resolved.

Now, do you think you could squash these commits? :sweat_smile:  There's some unrelated commits here, so it makes it really difficult to review.

**Comment by GuyKahlon** [comment]
Hey @jessesquires, How can I squash these commits after a few merges from the master?
Anyway, I have sent you a new PR.
Please let me know everything is ok and I'll close the current PR.

Thanks and sorry about all the mess.

**Comment by jessesquires** [comment]
Hey @GuyKahlon :smile: 

Looks like #1549 had even more unrelated commits :sweat_smile: 

Since this is for 8.0, I'll hold off on merging for now, and then left GitHub do the squash.

**Comment by jessesquires** [comment]
If you want to try again, i think this will help:
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

I *think* this is what you'll need to do, but :warning: be careful. Backup and changes first incase something goes wrong :smile: 

```
git checkout Support_RTL_Languages # checkout this branch
git rebase -i HEAD~11 # squash all 11 commits here into 1
git commit --amend # update commit message
git rebase develop # rebase on develop
git push origin Support_RTL_Languages --force # force push your branch to github
```

**Comment by GuyKahlon** [comment]
Closed due unrelated commits, replaced by #1550.

**Pull request closed without merging**
