### PR TITLE
a fix for #1268

### PR DESCRIPTION
**Pull request by Lucashuang0802**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____

## What's in this pull request?

> This is for PR #1669

### CODE REVIEW

**Comment by Lucashuang0802** [comment]
This is the PR that is able to merge without extra commits, #1669. @jessesquires

**Comment by Lucashuang0802** [comment]
@jessesquires Just remind you that this is ready to merge I think? Let me know if there is something wrong with it. Cheers~ 😃

**Comment by jessesquires** [comment]
Thanks @Lucashuang0802 ! 😄 

Just tested this patch and it doesn't seem to work. Showing the keyboard now adds a bunch of extra padding to the bottom inset...?

Going to close this for now until we find a better fix.

**Comment by Lucashuang0802** [comment]
I'm so sorry that I did not test it thoroughly. Without telling the customization, it seems to be tough to make padding. So, I create a new property `bottomContentAdditionalInset` just like `topContentAdditionalInset` to let developers to choose the customization they want. Already include a small sample in `viewDidLoad` from `DemoMessagesViewController`.

**Comment by Lucashuang0802** [comment]
https://github.com/Lucashuang0802/JSQMessagesViewController/commit/e7038e715a74236ddb18ad6a865844b032bae931 Sorry, I forget to include this.

**Comment by jessesquires** [comment]
👍 

See my comment: https://github.com/jessesquires/JSQMessagesViewController/issues/1268#issuecomment-149773956

Instead of a bunch of individual properties, we should provide 1 insets property

**Comment by Lucashuang0802** [comment]
Right, I did read that before I made the unfixed commit. I probably forgot to check it again. Sorry about that. It's updated and rebased already: https://github.com/Lucashuang0802/JSQMessagesViewController/commit/936ae77d57ebe1b4924c42ee339ba0e9d5091c12

**Comment by jessesquires** [comment]
submit a new PR? 😄

**Comment by Lucashuang0802** [comment]
@jessesquires not a problem, #1737

**Pull request closed without merging**
