### PR TITLE
Update Swift example to Xcode 8 GM Swift 3.0 syntax

### PR DESCRIPTION
**Pull request by gerbiljames**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊

## What's in this pull request?
Updated the Swift example project to Xcode 8 GM Swift 3.0 syntax
Fixed the SenderDisplayNameDefaultSetting test in the Swift example project
Disabled code signing on all targets in the Swift example project

**This fixes issue  #1824**

### CODE REVIEW

**Comment by Lucashuang0802** [comment]
Per comment here: #1608 (comment). I don't think it's an issue until XCode 8 get released officially.

**Comment by jessesquires** [comment]
Thanks @gerbiljames ! 👍 Generally looks good to me. 

One thing to change:

The migrator doesn't handle `NSIndexPath` very well. Everywhere where you see `(indexPath as NSIndexPath)` should be change to simply `indexPath`.

**Comment by gerbiljames** [comment]
Done.

I know that Xcode 8 isn't released officially yet, but iOS 10 is released tomorrow and there are unlikely to be any major changes to Swift syntax in the final Xcode 8 so I felt this PR would be useful, if not now, but sometime in the near future.

**Comment by jessesquires** [comment]
Thanks @gerbiljames ! 

Yep, we'll hold on to this and merge in a few days.

**Comment by jessesquires** [comment]
## Note: merge this after Xcode 8 final release

**Comment by MacMeDan** [comment]
I'm just glad you figured out that I don't know how to spell  'Wozniak' s name. 🤘

Awesome Work!

**Comment by realmike33** [comment]
will this be merged?

**Comment by jessesquires** [comment]
👍

**Pull request merged**
