### PR TITLE
Swift 2.0 interoperability

### LINKED ISSUE #776: Implement Objective-C nullability
From [Xcode 6.3 beta release notes](http://adcdownload.apple.com//Developer_Tools/Xcode_6.3_beta/Xcode_6.3_beta_Release_Notes.pdf):

>Objective-C APIs can now express the “nullability” of parameters, return types, properties, variables, etc.
>
>The nullability qualifiers affect the optionality of the Objective-C APIs when in Swift. Instead of being imported as implicitly-unwrapped optionals (e.g., UINib!), nonnull-qualified types are imported as non-optional (e.g., UINib) and nullable-qualified types are imported as optional...

### PR DESCRIPTION
**Pull request by hwaxxer**
Fixes #776 to facilitate Swift development.

* Adds `nullable` and `nonnullable`
* Use `strong` instead of `weak` for `IBOutlets` as per ["new" convention](http://stackoverflow.com/a/31395938/254422)
* Guarantee instantiated objects now that we can specify `nonnull` parameters

There are some tests that now generates warnings (for nullable parameters). We could probably remove these tests since the compiler will now generate warnings when passing nullable arguments. Let me know and I'll update this PR.

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks so much @hwaxxer ! :smile: 

Sorry so late to respond. Just bumped this back to the `8.0` milestone, instead of `7.2.1`. I just realized this will technically be a breaking change for anyone using Swift.

Once `7.2.1` is released, I'll get this merged :+1:

**Comment by grosch** [comment]
I think you need to completely break with this code when you move to Swift.  This library was written for Obj-C.  If you simply "convert" to Swift you make a suboptimal interface.  Lots of things you could take advantage of making cleaner you won't be able to do if you try to keep compatibility.

**Comment by jessesquires** [comment]
@grosch see https://github.com/MessageKit 😄 😄

**Comment by jessesquires** [comment]
@hwaxxer So sorry for the delay here. If you'd still like to support this PR and resolve the conflicts, I would love to merge it! 🎉

**Comment by jessesquires** [comment]
@MacMeDan this would be a good task if you want to take over. 😄

**Comment by hwaxxer** [comment]
@jessesquires A lot on my plate right now but I could maybe do it this weekend.

**Comment by jessesquires** [comment]
Thanks @hwaxxer ! No worries — there's no pressure. Just wanted to ask / give you the opportunity to merge if you wanted. 😄

**Comment by Lucashuang0802** [comment]
Isn't it the same #1654? LOL

**Comment by jessesquires** [comment]
Yep, thanks @Lucashuang0802 😄 

This is old and the work has been done on `develop`. Going to close.

Thanks again @hwaxxer !

**Pull request closed without merging**
