### PR TITLE
Swift example implementation

### PR DESCRIPTION
**Pull request by MacMeDan**
## Pull request checklist

- [✅] This fixes issue #<issue number>.
- [✅] All tests pass. Demo project builds and runs.
- [✅] I have resolved any merge conflicts.
- [✅] I have squashed my commits into 1 commit.
- [✅] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: :muscle::sunglasses::facepunch:

## What's in this pull request?
A Swift example implementing JSQMessagesViewController.
>...

### CODE REVIEW

**Comment by MacMeDan** [comment]
Some how trying to squash all my commits I just duplicated them. So I just made another branch and added all the changes in one commit. 😗💨

**Comment by jessesquires** [comment]
>Some how trying to squash all my commits I just duplicated them. So I just made another branch and added all the changes in one commit.

:smile: :smile: git is hard and confusing sometimes.

Looks like there are some issues though:
https://github.com/jessesquires/JSQMessagesViewController/pull/1481/commits

Also, some merge conflicts :grin:

**Comment by jessesquires** [comment]
This should help:
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by jessesquires** [comment]
replaced by #1491

**Pull request closed without merging**
