### PR TITLE
finish loading earlier messages method

### PR DESCRIPTION
**Pull request by kohtenko**
Resolves issue #307 

Great thanks to @marvin-yorke and his answer on http://stackoverflow.com/questions/25548257/uicollectionview-insert-cells-above-maintaining-position-like-messages-app/25579438#25579438

### CODE REVIEW

**Comment by kohtenko** [comment]
@jessesquires Travis CI test failed with too long expectation, but I sure it's because Travis machines are too slow.

**Comment by akhilcb** [comment]
Just wondering whether this is available yet. When can we expect this in cocoa pods? Looks like a critical feature in load earlier message.

**Comment by wdcurry** [comment]
I think i have missed the boat on this one, as this seems fairly basic. The button only allows you to act, and Jesse's stance is that the library is agnostic to delivery, so how would this be finished from the library's perspective? Is it not up to the coder to do what they want with the loaded earlier message? Willing as always to be wrong on this one ;)

**Comment by beribas** [comment]
Thanks @kohtenko! Worked for me, too. The only solution I could find which really worked w/o glitches. Just in case if someone needs swift version for updating:

```swift        
        let contentHeight = collectionView.contentSize.height
        let offsetY = collectionView.contentOffset.y
        let bottomOffset = contentHeight - offsetY
        
        let snapshot = UIImageView()
        snapshot.translatesAutoresizingMaskIntoConstraints = false
        view.insertSubview(snapshot, belowSubview: inputToolbar)
        snapshot.centerXAnchor.constraint(equalTo: collectionView.centerXAnchor).isActive = true
        snapshot.centerYAnchor.constraint(equalTo: collectionView.centerYAnchor, constant: collectionView.contentInset.top).isActive = true
        snapshot.widthAnchor.constraint(equalTo: collectionView.widthAnchor).isActive = true
        snapshot.heightAnchor.constraint(equalTo: collectionView.heightAnchor).isActive = true
        
        view.updateConstraints()
        view.layoutSubviews()

        UIView.performWithoutAnimation {
            UIGraphicsBeginImageContextWithOptions(self.collectionView.bounds.size, false, 0)
            collectionView.drawHierarchy(in: collectionView.bounds, afterScreenUpdates: true)
            let snapshotImage = UIGraphicsGetImageFromCurrentImageContext()
            UIGraphicsEndImageContext()
            
            snapshot.image = snapshotImage
            snapshot.isHidden = false
            
            self.collectionView.performBatchUpdates({
                self.collectionView.insertItems(at: indexPaths)  // create indexPaths before
            }, completion: { finished in
                self.collectionView.contentOffset = CGPoint(x: 0, y: self.collectionView.contentSize.height - bottomOffset)
                self.collectionView.collectionViewLayout.invalidateLayout()
                snapshot.isHidden = true
            })
        }
```

**Pull request closed without merging**
