### PR TITLE
Added a label method (for a text string or view) to JSQMediaItem

### PR DESCRIPTION
**Pull request by eliburke**
I love iMessage, but Facebook's Messenger definitely iterates at a faster pace. I like the labels they put on their media items, so I threw this together (over a glass of red wine so YMMV).
Call `JSQMediaItem:addLabelText` or `JSQMediaItem:addLabelView` from any subclass to put a label banner across the bottom of your media items. 

screen shot 2016-03-29 at 10 20 39 pm

As an example, I also added mediaLabelText and mediaLabelView properties to JSQMediaItem, and updated JSQPhotoItem to look for said properties when rendering the cachedImageView. If @jessesquires likes this PR we can trivially support them on video, location, etc

If you want clickable buttons, Giphy logos, etc, create your own view and set it up any way you want.

### CODE REVIEW

**Comment by eliburke** [comment]
@jessesquires I should probably anticipate your suggestion to create a JSQMediaItemLabelConfiguration class and add it to ... the collection obj?, and move the blur settings, edge insets, font, text color, background color, label auto-shrink, etc into said config class. Does that sound about right?

**Comment by eliburke** [comment]
I've re-worked this PR to move all of the rendering logic into a factory class. The default factory object initializer creates a standard bottom label, but can be modified to create a variety of other placements and effects. 
screen shot 2016-03-31 at 1 05 36 pm

**Comment by ljesus** [comment]
Waiting for this merge

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Pull request closed without merging**
