### PR TITLE
Support inverted mode

### PR DESCRIPTION
**Pull request by llz456**
Implement inverted mode as requested in #665. Fully backward compatible.

### CODE REVIEW

**Comment by llz456** [comment]
most the changes including storyboard are for the demo app.

**Comment by jessesquires** [comment]
Thanks @llz456 !

But I'm skeptical that we're solving the right problem here. See my comments at #665.

**Comment by llz456** [comment]
@jessesquires

Without inverted mode, it needs to render the first number of cells (to fill up screen), then last number of cells (to fill up screen) due to 'scroll-to-bottom' action. Here are the log messages from cellForItemAtIndexPath: method:

2015-11-17 21:13:39.011 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 0
2015-11-17 21:13:39.019 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 1
2015-11-17 21:13:39.023 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 2
2015-11-17 21:13:39.027 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 3
2015-11-17 21:13:39.059 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 4
2015-11-17 21:13:39.065 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 5
2015-11-17 21:13:39.070 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 6
2015-11-17 21:13:39.113 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 28
2015-11-17 21:13:39.115 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 29
2015-11-17 21:13:39.116 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 30
2015-11-17 21:13:39.118 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 31
2015-11-17 21:13:39.119 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 32
2015-11-17 21:13:39.121 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 33
2015-11-17 21:13:39.124 JSQMessages[64615:3392106] cellForItemAtIndexPath called for item 34

With inverted mode, it only needs to render the cells of most recent messages:

2015-11-17 21:15:17.462 JSQMessages[64680:3393855] cellForItemAtIndexPath called for item 0
2015-11-17 21:15:17.471 JSQMessages[64680:3393855] cellForItemAtIndexPath called for item 1
2015-11-17 21:15:17.475 JSQMessages[64680:3393855] cellForItemAtIndexPath called for item 2
2015-11-17 21:15:17.479 JSQMessages[64680:3393855] cellForItemAtIndexPath called for item 3
2015-11-17 21:15:17.482 JSQMessages[64680:3393855] cellForItemAtIndexPath called for item 4
2015-11-17 21:15:17.542 JSQMessages[64680:3393855] cellForItemAtIndexPath called for item 5
2015-11-17 21:15:17.547 JSQMessages[64680:3393855] cellForItemAtIndexPath called for item 6

Log messages explains how the annoying screen flicker effect happens. With inverted mode, no more flicker, and the initial rendering time gets cut into half (only render the cells that need to be rendered.) 
There is still huge user base out there running apps on slow devices. Any improvement to JSQMessages means a lot to those users.

I was investigating performance issues of some existing implementation of conversation page on slow devices. #665 just gave me idea of another area of further enhancement. Thanks, @chadpod :)

@jessesquires once you make TTTAttributedLabel, and inverted mode into 8.0 release, I will love to switch to JSQMessages for the app I'm working on. I really like JSQMessages, Easy to integrate, customize, and makes my code base slim! Thanks!

**Comment by jessesquires** [comment]
Thanks @llz456 ! :smile: 

For now, I don't think this is the direction we want to take the library, especially with some of the upcoming changes for the 8.0 roadmap.

I'm going to close this out, but we might consider this in the future!

**Pull request closed without merging**
